name: 🚀 Deploy website on push
  
on:
  push:
  workflow_dispatch:

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: windows-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: 🔨 Build Project
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        npm install --legacy-peer-deps
        npm run build
    
    - name: 📂 Sync files
      if: startsWith(github.ref, 'refs/tags/v')
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PWD }}
        protocol: ftp
        local-dir: 'build/'
        dangerous-clean-slate: true
